# Trigger builds on commits and merges to branch
trigger:
  batch: true
  branches:
    include:
    - develop

# Trigger builds on PRs to branch
pr:
  branches:
    include:
    - main

extends:
  template: ./Shared/azure-pipelines.yml